# Generated by Django 5.0.4 on 2024-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_options_remove_tasks_datetime_tasks_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['priority', 'complete', 'date', 'time']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'No Priority')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
